# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  MajorVersion: 1
  MinorVersion: 0.0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

stages:
- stage: Build
  jobs:
  - job: Build2
    pool: AzurePool            
    steps:
    - script: echo "hello to my first Build"
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: 'f264fb05-fdb0-48f5-8413-4707614a8f78'
        pipeline: '1'
        buildVersionToDownload: 'specific'
        buildId: '192'
        downloadType: 'specific'
        itemPattern: '**/tensorflow_java*.tar.gz'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(System.ArtifactsDirectory)/tensorflow_java_192.tar.gz/tensorflow_java_192.tar.gz'
        destinationFolder: '$(agent.builddirectory)'
        cleanDestinationFolder: false
      