# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  MajorVersion: 1
  MinorVersion: 0.0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

stages:
- stage: Build
  jobs:
  - job: Build2
    pool: AzurePool            
    steps:
    - script: echo "hello to my first Build"
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: 'f264fb05-fdb0-48f5-8413-4707614a8f78'
        pipeline: '1'
        buildVersionToDownload: 'specific'
        buildId: '192'
        downloadType: 'specific'
        itemPattern: '**/tensorflow_java*.tar.gz'
        downloadPath: '$(System.ArtifactsDirectory)'

    - bash: mkdir -p $(agent.builddirectory)/p/artifacts/tensorflow-java/libs
      displayName: Create a preparation directory      

    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(System.ArtifactsDirectory)/*.tar.gz'
        destinationFolder: '$(agent.builddirectory)/p'
        cleanDestinationFolder: false

    - bash: sudo bash /opt/linkedin/build_tf.sh --artifact_dir='$(agent.builddirectory)'/p --tensorflow_version='2.0.0' --lang='java'
      displayName: Create jar


    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'goyalankit'
        repositoryName: '$(Build.Repository.Name)'
        action: create
        target: $(Build.SourceVersion)
        tagSource: 'manual'
        tag: v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)-java
        changeLogCompareToRelease: lastFullRelease
        changeLogType: commitBased
        assets: $(agent.builddirectory)/p/artifacts/tensorflow-java/libs/libtensorflow.jar
