# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  MajorVersion: 1
  MinorVersion: 0.0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"

  - job: Build2
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"

- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world !!!"
- stage: qa_deploy
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'qa-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, qa world !!!"
