# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Configure GPG Key and create gradle properties file
      run: |
        mkdir -p ${HOME}/.gnupg/ ${HOME}/.gradle
        # Decode and create the private key file
        printf "${GPG_SIGNING_KEY}" | base64 --decode > ${HOME}/.gnupg/private.key
        chmod 500 ${HOME}/.gnupg/private.key
        # Try importing the key.
        gpg --import ${HOME}/.gnupg/private.key
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "Key1: $KEY1"
        cat > filename <<EOF
        hello from other $KEY1
        file contents ${KEY1}
        file contents $KEY1
        more contents ${KEY2}
        more contents "$KEY2"
        EOF
      env:
        KEY1: "value1"
        KEY2: "value2"
    - name: Display contents of the file created in the above step
      run: cat filename
